# fly.toml app configuration file generated for md3 on 2023-08-02T14:10:45-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "md3"
primary_region = "fra"
kill_signal = "SIGINT"
kill_timeout = "5s"

[build]
  image = "nginx"

[deploy]
  strategy = "canary"

[[services]]
  protocol = "tcp"
  internal_port = 80
  processes = ["app"]
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

  [services.concurrency]
    type = "connections"
    hard_limit = 25
    soft_limit = 20
